use FBD_1_ProductosClientes

--1. MOSTRAR TODOS LOS REGISTROS DE LA TABLA CLIENTES
SELECT * FROM Cliente

--2. MOSTRAR TODOS LOS REGISTROS DE LA TABLA PRODUCTOS
SELECT * FROM Productos

--3. MOSTRAR TODOS LOS REGISTROS DE LA TABLA PROVEEDORES
SELECT *FROM Proveedores

--4. MOSTRAR LOS NOMBRES DE LOS PRODUCTOS DE LA TABLA PRODUCTOS 
SELECT Nom_Producto from Productos

--5. MOSTRAR LOS DATOS DEL PRODUCTO CON CODIGO DE BARRAS: 150234570
SELECT Cod_Barra, Proveedores_RFC, Nom_Producto from Productos WHERE Cod_Barra=150234570

--6. MOSTRAR LOS DATOS DEL PROVEEDOR RFC: WERT
SELECT RFC, Nom_Proveedor FROM Proveedores WHERE RFC= 'WERT' 

--7. MOSTRAR LOS PROUCTOS QUE CONTENGAN EN SU NOMBRE LAS LETRAS SEGUIDAS DE "AN"
SELECT Nom_Producto from Productos WHERE Nom_Producto= 'AN'

--8. MOSTRAR LOS NOMBRES Y LA CANTIDAD DE LOS PRODUCTOS QUE HA COMPRADO EL CLIENTE "ANA"
SELECT P.Nom_Producto, COUNT (CP.Cliente_ID_Cliente) AS 'Cantidad Productos' FROM Clientes_has_Productos CP 
inner join Cliente C ON C.ID_Cliente = CP.Cliente_ID_Cliente 
inner join Productos P ON P.Cod_Barra = Productos_Cod_Barra 
WHERE C.Nom_Cliente = 'ANA' GROUP BY P.Nom_Producto, CP.Cliente_ID_Cliente


--9. ACTUALIZAR EL NOMBRE DEL CLIENTE "JUAN" POR EL DE "NAUJ"
UPDATE Cliente SET Nom_Cliente='NAUJ' WHERE Nom_Cliente='JUAN'

--10. ACTUALIZAR EL NOMBRE DEL PROVEEDOR "BIMBO" POR EL DE "OBMIB"
UPDATE Proveedores SET Nom_Proveedor='OBMIB' WHERE Nom_Proveedor='BIMBO'